name: ci

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  pull:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler:
        - gcc
        - clang
    steps:
    - uses: actions/checkout@v2
    - name: ${{ matrix.target }}
      run:
      - apt-get install -y ${{ matrix.target }}
      - CC=${{ matrix.target }} make test
